#define NAMEPLEER				TEXT("AudioPleer")

#define THIS							11000
#define IDC_BTNCLOSE					THIS + 1
#define IDC_COLORTEXTRED				THIS + 2
#define IDC_COLORTEXTGREEN				THIS + 3
#define IDC_COLORTEXTBLUE				THIS + 4
#define IDC_COLORWHITE					THIS + 5
#define IDC_COLORYELLOW 				THIS + 6
#define IDC_COLORBLUEVIOLET				THIS + 7
#define IDC_COLORYELLOW 				THIS + 8
#define IDC_COLORTURQUOISE				THIS + 9
#define IDC_SPECTR_AUTOCOLUMNS			THIS + 10
#define IDC_SPECTR_MANUALLYCOLUMNS		THIS + 11
#define COLOR_CONTOUR_RED				THIS + 12
#define COLOR_CONTOUR_GREEN				THIS + 13
#define COLOR_CONTOUR_BLUE				THIS + 14
#define COLOR_CONTOUR_WHITE				THIS + 15
#define COLOR_FILL_RED					THIS + 16
#define COLOR_FILL_GREEN				THIS + 17
#define COLOR_FILL_BLUE					THIS + 18
#define COLOR_FILL_WHITE				THIS + 19